import Image from "next/image";
import Link from "next/link";
import theme from "@/theme";

import { Stack, Typography } from "@mui/material";

const AboutContent = () => {
  return (
    <Stack
      flexDirection={"row"}
      gap={"100px"}
      alignItems={"center"}
      marginBottom={"300px"}
    >
      <Image
        src={"assets/img/preview.png"}
        width={570}
        height={434}
        alt="Preview Picture"
      />
      <Stack gap={"15px"}>
        <Typography variant="body1" color={theme.palette.blue.dark}>
          Users can add a tracking code to their GitHub profiles and see how
          many people have viewed their profile and on which days. This way, you
          can manage your profile more effectively and understand which content
          attracts the most interest from your visitors.
        </Typography>
        <Typography variant="body1" color={theme.palette.blue.dark}>
          The application works in a very straightforward way: The user adds a
          small piece of code generated by the app to their GitHub profile. When
          visitors access your profile, these visits are automatically recorded
          in the app. The system collects daily visitor data and displays it on
          your GitHub profile. This allows you to know who visited and when
          without the need for complex tools. Plus, there’s no need for any
          registration to use this system.
        </Typography>
        <Typography variant="body1" color={theme.palette.blue.dark}>
          You can also use{" "}
          <Link
            href={"https://github.com/orgs/githubvisitorstats/discussions"}
            target="_blank"
          >
            GitHub’s Discussions
          </Link>{" "}
          section to ask questions and share feedback about the app with the
          community, or get more information.
        </Typography>
      </Stack>
    </Stack>
  );
};

export default AboutContent;
