import Head from "next/head";

import { Container, Stack, Typography } from "@mui/material";
import { Header, SplashContent } from "@/components/organisms";
import {
  Button,
  IconButton,
  Input,
  SplashBackground,
} from "@/components/atoms";
import theme from "@/theme";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCopy } from "@fortawesome/free-regular-svg-icons";
import { FeatureBox, TitleSection } from "@/components/molecules";
import {
  faCoins,
  faGear,
  faUserSlash,
} from "@fortawesome/free-solid-svg-icons";
import Image from "next/image";
import Link from "next/link";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Github Visitor Stats - A tool to track visits to your GitHub profile
        </title>
        <meta
          name="description"
          content="A tool to track visits to your GitHub profile"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <UnderConstruction /> */}
      <SplashBackground>
        <Container>
          <Header />
          <SplashContent />
        </Container>
      </SplashBackground>
      <Container>
        <Stack
          flexDirection={"row"}
          gap={"40px"}
          marginTop={"-100px"}
          marginBottom={"300px"}
        >
          <FeatureBox
            icon={faCoins}
            title={"Free to Use"}
            detail={
              "You don’t need to pay anything to use GitHub Visitor Stats! All features are completely free with unlimited access. Monitoring your profile is now easy and cost-free!"
            }
          />
          <FeatureBox
            icon={faUserSlash}
            title={"No Registration Required"}
            detail={
              "You don’t need to create an account to use GitHub Visitor Stats! Start using it right away without the hassle of signing up."
            }
          />
          <FeatureBox
            icon={faGear}
            title={"Simple Integration"}
            detail={
              "Easily add a dynamic visitor badge to your GitHub profile with just a few lines of code. Start tracking visitors in seconds!"
            }
          />
        </Stack>
        <TitleSection
          category={"GITHUB VISITOR STATS"}
          title={"The Easy Way to Track Your Profile"}
          detail={
            "GitHub Visitor Stats is a simple web application that allows you to track who has visited your GitHub profile."
          }
        />
        <Stack
          flexDirection={"row"}
          gap={"100px"}
          alignItems={"center"}
          marginBottom={"300px"}
        >
          <Image
            src={"assets/img/preview.png"}
            width={570}
            height={434}
            alt="Preview Picture"
          />
          <Stack gap={"15px"}>
            <Typography variant="body1" color={theme.palette.blue.dark}>
              Users can add a tracking code to their GitHub profiles and see how
              many people have viewed their profile and on which days. This way,
              you can manage your profile more effectively and understand which
              content attracts the most interest from your visitors.
            </Typography>
            <Typography variant="body1" color={theme.palette.blue.dark}>
              The application works in a very straightforward way: The user adds
              a small piece of code generated by the app to their GitHub
              profile. When visitors access your profile, these visits are
              automatically recorded in the app. The system collects daily
              visitor data and displays it on your GitHub profile. This allows
              you to know who visited and when without the need for complex
              tools. Plus, there’s no need for any registration to use this
              system.
            </Typography>
            <Typography variant="body1" color={theme.palette.blue.dark}>
              You can also use{" "}
              <Link
                href={"https://github.com/orgs/githubvisitorstats/discussions"}
                target="_blank"
              >
                GitHub’s Discussions
              </Link>{" "}
              section to ask questions and share feedback about the app with the
              community, or get more information.
            </Typography>
          </Stack>
        </Stack>
      </Container>
      <Stack bgcolor={theme.palette.grey.dark}>
        <Container>
          <Stack
            padding={"150px 0px"}
            sx={{
              maxWidth: "700px", // Varsayılan olarak %100 genişlik
              "@media (min-width: 576px)": {
                maxWidth: "100%", // small
              },
              "@media (min-width: 768px)": {
                maxWidth: "100%", // medium
              },
              "@media (min-width: 992px)": {
                maxWidth: "400px", // large
              },
              "@media (min-width: 1200px)": {
                maxWidth: "600px", // x-large
              },
              "@media (min-width: 1400px)": {
                maxWidth: "700px", // xx-large
              },
              position: "relative",
              zIndex: 1,
            }}
          >
            <Typography variant="h5" color={theme.palette.white.main}>
              Got Questions? Join the Discussion!
            </Typography>
            <Typography
              variant="body1"
              color={theme.palette.grey.light}
              marginTop={"5px"}
              marginBottom={"50px"}
            >
              Share your questions, suggestions, or feedback with us by joining
              the Discussions area on GitHub. Collaborate with our community to
              solve issues and learn more!
            </Typography>
            <Button variant="contained" style={{ gap: "15px" }}>
              <FontAwesomeIcon
                icon={faGithub}
                fontSize={"20px"}
                color={theme.palette.white.main}
              />
              GitHub Discussions
            </Button>
          </Stack>
          <Stack
            sx={{
              position: "absolute",
              width: "auto",
              height: "100%",
              top: 0,
              right: 0,
              "@media (min-width: 768px)": {
                maxWidth: "100%", // medium
              },
            }}
          >
            <Stack
              sx={{
                position: "absolute",
                left: 0,
                top: 0,
                width: "100%",
                height: "100%",
                backgroundColor: theme.palette.grey.dark,
                opacity: 0.8,
              }}
            ></Stack>
            <Image
              style={{ width: "auto", height: "100%" }}
              src={"assets/img/discussion-picture.png"}
              width={730}
              height={500}
              alt="Discussion Picture"
            />
          </Stack>
        </Container>
      </Stack>
      <footer
        style={{
          backgroundImage: `linear-gradient(to bottom, ${theme.palette.purple.main}, ${theme.palette.purple.dark})`,
        }}
      >
        <Container>
          <Stack padding={"30px 0px"}>
            <Stack
              flexDirection={"row"}
              justifyContent={"space-between"}
              borderBottom={`1px solid rgba(255, 255, 255, 0.1)`}
              paddingBottom={"30px"}
              marginBottom={"30px"}
            >
              <Stack maxWidth={"222px"} gap={"30px"}>
                <Link href={"/"}>
                  <Image
                    src={"assets/img/logo-white.svg"}
                    width={40}
                    height={40}
                    alt="Github Visitor Stats Logo"
                  />
                </Link>
                <Typography variant="overline" color={theme.palette.white.main}>
                  GitHub Visitor Stats is a simple web application that allows
                  you to track who has visited your GitHub profile.
                </Typography>
              </Stack>
              <Stack>
                <Link
                  href={"https://github.com/githubvisitorstats"}
                  target="_blank"
                >
                  <FontAwesomeIcon
                    icon={faGithub}
                    fontSize={"21px"}
                    color={theme.palette.grey.light}
                  />
                </Link>
              </Stack>
            </Stack>
            <Stack flexDirection={"row"} justifyContent={"space-between"}>
              <Typography
                variant="overline"
                fontSize={"13px"}
                lineHeight={"normal"}
                color={theme.palette.grey.light}
              >
                © 2024 Yasin B. Kalkan
              </Typography>
              <Stack flexDirection={"row"} gap={"30px"}>
                <Typography variant="button">
                  <Link href={""}>How It Works</Link>
                </Typography>
                <Typography variant="button">
                  <Link href={""}>FAQ</Link>
                </Typography>
                <Typography variant="button">
                  <Link href={""}>Privacy Policy</Link>
                </Typography>
              </Stack>
            </Stack>
          </Stack>
        </Container>
      </footer>
    </>
  );
}
