import Head from "next/head";
import theme from "@/theme";

import { ThemeProvider } from "@mui/material";
import { UnderConstruction } from "@/components/templates";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-TB8PH2QP8F"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-TB8PH2QP8F');
        </script>
      </Head>
      <ThemeProvider theme={theme}>
        <UnderConstruction />
      </ThemeProvider>
    </>
  );
}
